/* 物料主文件 */
create table T_DSPRODUCT
(
	PRODID VARCHAR2(20) not null
		primary key,
	CLASSID VARCHAR2(20) not null,
	CLASSNAME VARCHAR2(20) not null,
	PRODNAME VARCHAR2(20) not null,
	UNITID VARCHAR2(20) default NULL not null,
	UNIT VARCHAR2(20) not null,
	PRODSIZE VARCHAR2(20),
	BARCODEID VARCHAR2(20),
	ENGNAME VARCHAR2(20),
	SUGGESTPRICE NUMBER default 0.00 not null,
	SALESPRICEA NUMBER default 0.00 not null,
	SALESPRICEB NUMBER default 0.00 not null,
	SALESPRICEC NUMBER default 0.00 not null,
	SALESPRICED NUMBER default 0.00 not null,
	SALESPRICEE NUMBER default 0.00 not null,
	STDPRICE NUMBER default 0.00 not null,
	CURRID VARCHAR2(20) not null,
	CURRNAME VARCHAR2(20) not null,
	PRODFORM VARCHAR2(20),
	PRICEOFTAX NUMBER(1) default 0 not null,
	TAXITEMSID VARCHAR2(20),
	TAXITEMSNAME VARCHAR2(20),
	BUSITAXRATE NUMBER default 17.00 not null,
	ADVANCEDAYS NUMBER(22) default 0 not null,
	MAJORSUPPLIER VARCHAR2(20),
	MAJORSUPPLIERNAME VARCHAR2(20),
	BATCHUSED NUMBER(1),
	EFFECTDATEUSED NUMBER(1),
	VALIDDATEUSED NUMBER(1),
	DEFVAKLIDDAY NUMBER(22) default 0 not null,
	SAFEQTY NUMBER(22) default 0 not null,
	BSTDCOST NUMBER default 0.00,
	BOUTSTOCKDAY DATE,
	BINSTOCKDAY DATE,
	SLUGGISHDAYS NUMBER(22) default 0 not null,
	INVALIDDATE DATE,
	UDEF1 VARCHAR2(20),
	UDEF2 VARCHAR2(20),
	PRODDESC VARCHAR2(255)
)
/
/* 物料类别 */
create table T_DSPRODUCTCLASS
(
	CLASSID VARCHAR2(20) not null
		primary key,
	CLASSNAME VARCHAR2(20) not null,
	ENGNAEM VARCHAR2(20),
	ACCINVENTORYID VARCHAR2(20),
	ACCINVENTORYNAME VARCHAR2(20),
	ACCSALEID VARCHAR2(20),
	ACCSALENAME VARCHAR2(20),
	ACCSALECOSTID VARCHAR2(20),
	ACCSALECOSTNAME VARCHAR2(20),
	SENDOUTWAREID VARCHAR2(20),
	SENDOUTWARENAME VARCHAR2(20),
	GIFTEXPENSEID VARCHAR2(20),
	GIFTEXPENSENAME VARCHAR2(20),
	OTHERINCOMEID VARCHAR2(20),
	OTHERINCOMENAME VARCHAR2(20),
	OTHEREXPENSEID VARCHAR2(20),
	OTHEREXPENSENAME VARCHAR2(20),
	OTHERCOSTID VARCHAR2(20),
	OTHERCOSTNAME VARCHAR2(20),
	MOME VARCHAR2(255)
)
/
/* 销售出库单主表 */
create table T_DSDSSALEMAIN
(
	BILLNO VARCHAR2(20) not null
		primary key,
	BILLDATE DATE not null,
	CUSTID VARCHAR2(20) not null,
	CUSTSHORTNAME VARCHAR2(20),
	ADDRID VARCHAR2(20),
	CUSTADDRESS VARCHAR2(255),
	SALECLASSID VARCHAR2(20),
	SALECLASSNAME VARCHAR2(20),
	PRICEOFTAX NUMBER(22) default 0 not null,
	WAREID VARCHAR2(20) not null,
	WARENAME VARCHAR2(20),
	CURRID VARCHAR2(20) not null,
	CURRNAME VARCHAR2(20),
	EXCHRATE NUMBER default 0.0000 not null,
	UDEF1 VARCHAR2(20),
	UDEF2 VARCHAR2(20),
	REMARK VARCHAR2(255),
	SALESID VARCHAR2(20) not null,
	SALESNAME VARCHAR2(20),
	DEPARTID VARCHAR2(20) not null,
	DEPARTNAME VARCHAR2(20),
	PROJECTID VARCHAR2(20),
	PROJECTNAME VARCHAR2(20),
	MAKER VARCHAR2(20) not null,
	MAKERNAME VARCHAR2(20),
	PERMITTER VARCHAR2(20),
	PERMITTERNAME VARCHAR2(20)
)
/
/* 销售出库单详表 */
create table T_DSDSSALESUB
(
	BILLNO VARCHAR2(20) not null,
	SERNO NUMBER(22) not null
		primary key,
	PRODID VARCHAR2(20) not null,
	PRODNAME VARCHAR2(20) not null,
	PRODSIZE VARCHAR2(20),
	SUNIT VARCHAR2(20) not null,
	SQUANTITY NUMBER(22) not null,
	OLDPRICE NUMBER not null,
	DISCOUNT NUMBER default 100 not null,
	SPRICE NUMBER not null,
	AMOUNT NUMBER not null,
	TAXRATE NUMBER default 17.00 not null,
	TAXAMT NUMBER not null,
	AMOUNTATAX NUMBER not null,
	ISGIFT NUMBER(22) default 0 not null,
	ITEMREMARK VARCHAR2(255),
	TRANTYPE VARCHAR2(20),
	TRANTYPENAME VARCHAR2(20),
	FORMNO VARCHAR2(20),
	CUSTBILLNO VARCHAR2(20)
)
/
/* 供应商主文件 */
create table T_DSDATASET1
(
	ID VARCHAR2(20) not null
		primary key,
	FULLNAME VARCHAR2(20) not null,
	SHORTNAME VARCHAR2(20) not null,
	ENGFULLNAME VARCHAR2(20),
	ENGSHORTNAME VARCHAR2(20),
	FUNDSATTRIBUTION VARCHAR2(20) not null,
	CLASSID VARCHAR2(20),
	CLASSNAME VARCHAR2(20),
	AREAID VARCHAR2(20),
	AREANAME VARCHAR2(20),
	CURRENCYID VARCHAR2(20),
	CURRENCYNAME VARCHAR2(20),
	CLIEFNAME VARCHAR2(20),
	LINKMAN VARCHAR2(20),
	TELEPHONE1 VARCHAR2(20),
	TELEPHONE2 VARCHAR2(20),
	TELEPHONE3 VARCHAR2(20),
	MOBILETEL VARCHAR2(20),
	BANKACCOUNT VARCHAR2(20),
	BANKID VARCHAR2(20),
	BANKNAME VARCHAR2(20),
	PERSONID VARCHAR2(20) not null,
	PERSONNAME VARCHAR2(20),
	TAXNO VARCHAR2(20),
	CAPITALIZATION NUMBER default 0 not null,
	INDUSTRIALCLASS VARCHAR2(20),
	EMAIL VARCHAR2(20),
	WEBADDRESS VARCHAR2(20),
	FAXNO VARCHAR2(20),
	EARLIESTTRADEDATE DATE,
	FIRSTTRADEDATE DATE,
	PRICEOFTAX NUMBER(22) default 0 not null,
	INVALIDDATE DATE,
	AMOUNTQUOTA NUMBER(22) default 0.00 not null,
	RECVWAY VARCHAR2(20) default '货到' not null,
	DISTDAYS NUMBER(22) default 0 not null,
	DAYOFCLOSE NUMBER(22) default 31 not null,
	CREDITLEVEL VARCHAR2(20) default 'A' not null,
	STARTADVRECV NUMBER default 0.00 not null,
	STARTRECEIVABLE NUMBER default 0.00 not null,
	CURADVRECV NUMBER default 0.00 not null,
	CURRECEIVABLE NUMBER default 0.00 not null,
	ACCADVRECV VARCHAR2(20),
	ACCADVRECVNAME VARCHAR2(20),
	ACCRECEIVABLE VARCHAR2(20),
	ACCRECEIVABLENAME VARCHAR2(20),
	ACCRECEIVABLETEMP VARCHAR2(20),
	ACCRECEIVABLETEMPNAME VARCHAR2(20),
	ADDFIELD1 VARCHAR2(20),
	ADDFIELD2 VARCHAR2(20),
	MEMO VARCHAR2(255)
)
/
/* 供应商地址 */
create table T_DSDATASET2
(
	ID VARCHAR2(20) not null,
	ADDRID VARCHAR2(20) not null
		primary key,
	ADDRESS VARCHAR2(20),
	ZIPCODE VARCHAR2(20),
	LINKMAN VARCHAR2(20),
	LINKMANPROF VARCHAR2(20),
	TELEPHONE VARCHAR2(20),
	FAXNO VARCHAR2(20),
	WALKADDR VARCHAR2(20),
	MEMO VARCHAR2(255)
)
/
/* 库存台账 */
create table T_DSDSWARETRANSACTION
(
	TRANTYPE VARCHAR2(20) not null,
	FORMNO VARCHAR2(20) not null,
	LINEID NUMBER(22) not null
		primary key,
	WAREHOUSEID VARCHAR2(20) not null,
	PRODID VARCHAR2(20) not null,
	QUANTITY NUMBER(22),
	PRICE NUMBER,
	AMOUNT NUMBER,
	BILLDATE DATE not null
)
/
/* 库存总账 */
create table T_DSDSWAREAMOUNT
(
	WAREHOUSEID VARCHAR2(20) not null,
	PRODID VARCHAR2(20) not null,
	BQUANTITY NUMBER(22) default 0 not null,
	BAVGCOST NUMBER default 0.00 not null,
	BALLCOST NUMBER default 0.00 not null,
	QUANTITY NUMBER(22) default 0 not null,
	CAVGCOST NUMBER default 0.00 not null,
	CALLCOST NUMBER default 0.00 not null
)
/

